"""Backup of the proven working Beta prototype.

This is a verbatim copy of ~/video-booth/app/booth.py as confirmed working
on the actual Raspberry Pi hardware. It is kept here for reference and as
the fallback known-good implementation, per PROJECT_SPEC.md's instruction
to back up the original script before refactoring.

Do not edit this file. It is not part of the video_guestbook package and
is not imported or tested. The video_guestbook package incorporates this
script's proven behavior (in particular: releasing the camera before
ffmpeg opens it, and reopening it afterward with retries; ffmpeg audio-sync
flags; and the stdin 'q' + SIGINT stop sequence).
"""

import cv2
import os
import signal
import subprocess
import sys
import time
from datetime import datetime

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

CAMERA_DEVICE = "/dev/video0"
CAMERA_NUMBER = 0
AUDIO_DEVICE = "plughw:3,0"

WIDTH = 1280
HEIGHT = 720
FPS = 30
COUNTDOWN_SECONDS = 3
MAX_RECORDING_SECONDS = 90

BASE_DIR = os.path.expanduser("~/video-booth")
RECORDINGS_DIR = os.path.join(BASE_DIR, "recordings")
LOGS_DIR = os.path.join(BASE_DIR, "logs")

os.makedirs(RECORDINGS_DIR, exist_ok=True)
os.makedirs(LOGS_DIR, exist_ok=True)

WINDOW_NAME = "Video Guestbook Beta 1.1"

camera = None
ffmpeg_process = None
ffmpeg_log_file = None

last_frame = None
current_filename = None

state = "READY"
state_started = time.monotonic()
recording_started = 0.0
stop_requested_at = 0.0


# ------------------------------------------------------------
# Drawing
# ------------------------------------------------------------

def draw_centered(frame, text, y, size=1.0, thickness=3):
    text_size = cv2.getTextSize(
        text,
        cv2.FONT_HERSHEY_SIMPLEX,
        size,
        thickness,
    )[0]

    x = max(10, (frame.shape[1] - text_size[0]) // 2)

    cv2.putText(
        frame,
        text,
        (x, y),
        cv2.FONT_HERSHEY_SIMPLEX,
        size,
        (255, 255, 255),
        thickness,
        cv2.LINE_AA,
    )


def darken(frame, amount=0.45):
    return cv2.convertScaleAbs(frame, alpha=amount, beta=0)


# ------------------------------------------------------------
# Camera
# ------------------------------------------------------------

def open_camera():
    global camera

    camera = cv2.VideoCapture(CAMERA_NUMBER, cv2.CAP_V4L2)

    if not camera.isOpened():
        camera = None
        return False

    camera.set(
        cv2.CAP_PROP_FOURCC,
        cv2.VideoWriter_fourcc(*"MJPG"),
    )
    camera.set(cv2.CAP_PROP_FRAME_WIDTH, WIDTH)
    camera.set(cv2.CAP_PROP_FRAME_HEIGHT, HEIGHT)
    camera.set(cv2.CAP_PROP_FPS, FPS)
    camera.set(cv2.CAP_PROP_BUFFERSIZE, 1)

    return True


def close_camera():
    global camera

    if camera is not None:
        camera.release()
        camera = None


def reopen_camera_with_retry():
    close_camera()

    for _ in range(10):
        if open_camera():
            return True

        time.sleep(0.3)

    return False


# ------------------------------------------------------------
# FFmpeg recording
# ------------------------------------------------------------

def start_recording():
    global ffmpeg_process
    global ffmpeg_log_file
    global current_filename
    global recording_started

    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

    current_filename = os.path.join(
        RECORDINGS_DIR,
        f"message_{timestamp}.mp4",
    )

    log_filename = os.path.join(
        LOGS_DIR,
        f"message_{timestamp}.log",
    )

    ffmpeg_log_file = open(log_filename, "w", encoding="utf-8")

    command = [
        "ffmpeg",
        "-y",

        "-thread_queue_size", "512",
        "-use_wallclock_as_timestamps", "1",
        "-f", "v4l2",
        "-input_format", "h264",
        "-video_size", f"{WIDTH}x{HEIGHT}",
        "-framerate", str(FPS),
        "-i", CAMERA_DEVICE,

        "-thread_queue_size", "512",
        "-use_wallclock_as_timestamps", "1",
        "-f", "alsa",
        "-i", AUDIO_DEVICE,

        "-map", "0:v:0",
        "-map", "1:a:0",

        "-c:v", "copy",

        "-c:a", "aac",
        "-b:a", "160k",
        "-ar", "48000",
        "-ac", "1",
        "-af", "aresample=async=1:first_pts=0",

        "-avoid_negative_ts", "make_zero",
        "-movflags", "+faststart",

        current_filename,
    ]

    ffmpeg_process = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        stdout=subprocess.DEVNULL,
        stderr=ffmpeg_log_file,
    )

    recording_started = time.monotonic()
    print(f"Recording: {current_filename}")


def request_recording_stop():
    global stop_requested_at

    if ffmpeg_process is not None and ffmpeg_process.poll() is None:
        try:
            ffmpeg_process.stdin.write(b"q\n")
            ffmpeg_process.stdin.flush()
        except (AttributeError, BrokenPipeError, OSError):
            ffmpeg_process.send_signal(signal.SIGINT)

        stop_requested_at = time.monotonic()


def finish_recording_process():
    global ffmpeg_process
    global ffmpeg_log_file

    result = None

    if ffmpeg_process is not None:
        result = ffmpeg_process.poll()

    if result is not None:
        ffmpeg_process = None

        if ffmpeg_log_file is not None:
            ffmpeg_log_file.close()
            ffmpeg_log_file = None

    return result


def force_stop_recording():
    global ffmpeg_process
    global ffmpeg_log_file

    if ffmpeg_process is not None and ffmpeg_process.poll() is None:
        ffmpeg_process.send_signal(signal.SIGINT)

        try:
            ffmpeg_process.wait(timeout=8)
        except subprocess.TimeoutExpired:
            ffmpeg_process.terminate()

            try:
                ffmpeg_process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                ffmpeg_process.kill()

    ffmpeg_process = None

    if ffmpeg_log_file is not None:
        ffmpeg_log_file.close()
        ffmpeg_log_file = None


# ------------------------------------------------------------
# App initialization
# ------------------------------------------------------------

if not open_camera():
    print("ERROR: Could not open /dev/video0")
    sys.exit(1)

cv2.namedWindow(WINDOW_NAME, cv2.WINDOW_NORMAL)
cv2.setWindowProperty(
    WINDOW_NAME,
    cv2.WND_PROP_FULLSCREEN,
    cv2.WINDOW_FULLSCREEN,
)

print("SPACE = start/stop")
print("Q or ESC = exit")


# ------------------------------------------------------------
# Main loop
# ------------------------------------------------------------

try:
    while True:
        now = time.monotonic()

        # Read live camera frames only when FFmpeg is not using the camera.
        if state not in ("RECORDING", "SAVING"):
            if camera is not None:
                success, frame = camera.read()

                if success:
                    last_frame = frame

        if last_frame is None:
            display = cv2.UMat(HEIGHT, WIDTH, cv2.CV_8UC3).get()
        else:
            display = last_frame.copy()

        key = cv2.waitKey(1) & 0xFF

        if key in (ord("q"), 27):
            break

        # ----------------------------------------------------
        # READY
        # ----------------------------------------------------

        if state == "READY":
            overlay = display.copy()

            cv2.rectangle(
                overlay,
                (120, HEIGHT - 190),
                (WIDTH - 120, HEIGHT - 45),
                (20, 20, 20),
                -1,
            )

            display = cv2.addWeighted(
                overlay,
                0.65,
                display,
                0.35,
                0,
            )

            draw_centered(
                display,
                "VIDEO GUESTBOOK",
                HEIGHT - 130,
                1.3,
                3,
            )

            draw_centered(
                display,
                "Press SPACE to leave a message",
                HEIGHT - 78,
                0.9,
                2,
            )

            if key == ord(" "):
                state = "COUNTDOWN"
                state_started = now

        # ----------------------------------------------------
        # COUNTDOWN
        # ----------------------------------------------------

        elif state == "COUNTDOWN":
            elapsed = now - state_started
            remaining = COUNTDOWN_SECONDS - int(elapsed)

            display = darken(display, 0.55)

            if remaining > 0:
                draw_centered(
                    display,
                    str(remaining),
                    390,
                    6.0,
                    12,
                )

                draw_centered(
                    display,
                    "Get ready",
                    500,
                    1.1,
                    3,
                )
            else:
                # Release OpenCV before FFmpeg takes the camera.
                close_camera()
                time.sleep(0.25)

                try:
                    start_recording()
                    state = "RECORDING"
                    state_started = now
                except Exception as error:
                    print(f"ERROR starting recording: {error}")
                    reopen_camera_with_retry()
                    state = "ERROR"
                    state_started = now

        # ----------------------------------------------------
        # RECORDING
        # ----------------------------------------------------

        elif state == "RECORDING":
            elapsed = now - recording_started

            display = darken(display, 0.62)

            cv2.circle(
                display,
                (55, 55),
                18,
                (0, 0, 255),
                -1,
            )

            cv2.putText(
                display,
                f"RECORDING   {elapsed:05.1f}s",
                (90, 68),
                cv2.FONT_HERSHEY_SIMPLEX,
                1.0,
                (255, 255, 255),
                3,
                cv2.LINE_AA,
            )

            draw_centered(
                display,
                "Press SPACE to stop and save",
                HEIGHT - 60,
                0.9,
                3,
            )

            # Detect an unexpected FFmpeg failure.
            if ffmpeg_process is not None:
                result = ffmpeg_process.poll()

                if result is not None:
                    finish_recording_process()
                    reopen_camera_with_retry()
                    state = "ERROR"
                    state_started = now

            if (
                key == ord(" ")
                or elapsed >= MAX_RECORDING_SECONDS
            ):
                request_recording_stop()
                state = "SAVING"
                state_started = now

        # ----------------------------------------------------
        # SAVING
        # ----------------------------------------------------

        elif state == "SAVING":
            display = darken(display, 0.35)

            draw_centered(
                display,
                "SAVING MESSAGE",
                320,
                1.6,
                4,
            )

            draw_centered(
                display,
                "Please wait...",
                390,
                1.0,
                3,
            )

            result = finish_recording_process()

            if result is not None:
                file_is_valid = (
                    current_filename is not None
                    and os.path.exists(current_filename)
                    and os.path.getsize(current_filename) > 10000
                )

                print(f"FFmpeg exit code: {result}")

                reopen_camera_with_retry()

                if file_is_valid:
                    print(f"Saved: {current_filename}")
                    state = "SAVED"
                else:
                    print("ERROR: Recording did not save correctly.")
                    state = "ERROR"

                state_started = now

            elif (
                stop_requested_at > 0
                and now - stop_requested_at > 10
            ):
                force_stop_recording()
                reopen_camera_with_retry()
                state = "ERROR"
                state_started = now

        # ----------------------------------------------------
        # SAVED
        # ----------------------------------------------------

        elif state == "SAVED":
            display = darken(display, 0.45)

            draw_centered(
                display,
                "MESSAGE SAVED",
                320,
                1.7,
                4,
            )

            draw_centered(
                display,
                "Thank you!",
                390,
                1.1,
                3,
            )

            if now - state_started >= 3:
                state = "READY"
                state_started = now

        # ----------------------------------------------------
        # ERROR
        # ----------------------------------------------------

        elif state == "ERROR":
            display = darken(display, 0.35)

            draw_centered(
                display,
                "RECORDING ERROR",
                320,
                1.5,
                4,
            )

            draw_centered(
                display,
                "Press SPACE to return",
                390,
                1.0,
                3,
            )

            if key == ord(" "):
                if camera is None:
                    reopen_camera_with_retry()

                state = "READY"
                state_started = now

        cv2.imshow(WINDOW_NAME, display)

finally:
    force_stop_recording()
    close_camera()
    cv2.destroyAllWindows()
